name: fbtl_screenshots
description: A package for taking screenshots of Flutter apps using Firebase Test Lab.
version: 0.0.2
repository: https://github.com/speaking-in-code/fbtl_screenshots

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.15
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: net.speakingincode.fbtl_screenshots
        pluginClass: FbtlScreenshotsPlugin
